# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20171001_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'MySubsciber', 'verbose_name_plural': 'MySubscibers'},
        ),
    ]
